# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sigsh\Documents\testPyQt5\ToggleMenu\ToggleMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToggleMenu(object):
    def setupUi(self, ToggleMenu):
        ToggleMenu.setObjectName("ToggleMenu")
        ToggleMenu.resize(1021, 567)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/airplay.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ToggleMenu.setWindowIcon(icon)
        ToggleMenu.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.verticalLayout = QtWidgets.QVBoxLayout(ToggleMenu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame = QtWidgets.QFrame(ToggleMenu)
        self.top_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_frame.setStyleSheet("background-color: rgb(35,35,35);")
        self.top_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.top_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_toggle_menu = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_toggle_menu.sizePolicy().hasHeightForWidth())
        self.pushButton_toggle_menu.setSizePolicy(sizePolicy)
        self.pushButton_toggle_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_toggle_menu.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_toggle_menu.setStyleSheet("QPushButton{\n"
"border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(45, 45, 45);\n"
"}\n"
"QPushButton:pressed{\n"
"/*background-color: rgb(85,170, 255);*/\n"
"background: rgb(85, 170, 255);\n"
"}")
        self.pushButton_toggle_menu.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_toggle_menu.setIcon(icon1)
        self.pushButton_toggle_menu.setObjectName("pushButton_toggle_menu")
        self.horizontalLayout_2.addWidget(self.pushButton_toggle_menu)
        self.horizontalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.top_frame)
        self.buttom_frame = QtWidgets.QFrame(ToggleMenu)
        self.buttom_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttom_frame.setObjectName("buttom_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.buttom_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_left_mepu = QtWidgets.QFrame(self.buttom_frame)
        self.frame_left_mepu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_mepu.setMaximumSize(QtCore.QSize(155, 16777215))
        self.frame_left_mepu.setStyleSheet("background-color: rgb(35,35,35);")
        self.frame_left_mepu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_mepu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_mepu.setObjectName("frame_left_mepu")
        self.frame_2 = QtWidgets.QFrame(self.frame_left_mepu)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 155, 120))
        self.frame_2.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(155, 16777215))
        self.frame_2.setStyleSheet("QPushButton{\n"
"\n"
"background-repeat: no-repeat;\n"
"background-position: left;\n"
"background-origin: content;\n"
"padding-left: 25px;\n"
"\n"
"border:none;\n"
"color: rgb(255,255,255);\n"
"background-color: rgb(35,35,35);\n"
"font-size: 12px;\n"
"padding-right: -40px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(45, 45, 45);\n"
"}\n"
"QPushButton:checked{\n"
"padding-left: 21px;\n"
"border-left: 4px solid rgb(85, 170, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_home = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_home.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_home.setFont(font)
        self.pushButton_home.setStyleSheet("QPushButton{\n"
"background-image: url(:/icons/home.svg);\n"
"}\n"
"")
        self.pushButton_home.setCheckable(True)
        self.pushButton_home.setChecked(True)
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout_3.addWidget(self.pushButton_home)
        self.pushButton_user = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_user.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_user.setStyleSheet("QPushButton{\n"
"background-image: url(:/icons/user.svg);\n"
"\n"
"}")
        self.pushButton_user.setCheckable(True)
        self.pushButton_user.setChecked(False)
        self.pushButton_user.setObjectName("pushButton_user")
        self.verticalLayout_3.addWidget(self.pushButton_user)
        self.pushButton_setting = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_setting.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_setting.setStyleSheet("QPushButton{\n"
"background-image: url(:/icons/settings.svg);\n"
"\n"
"}")
        self.pushButton_setting.setCheckable(True)
        self.pushButton_setting.setChecked(False)
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.verticalLayout_3.addWidget(self.pushButton_setting)
        self.horizontalLayout_3.addWidget(self.frame_left_mepu)
        self.frame_pages = QtWidgets.QFrame(self.buttom_frame)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_pages)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setStyleSheet("font: 28pt \"Cascadia Mono\";\n"
"qproperty-alignment: AlignCenter;\n"
"color: white;")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.textEdit = QtWidgets.QTextEdit(self.page_3)
        self.textEdit.setGeometry(QtCore.QRect(230, 180, 271, 51))
        self.textEdit.setObjectName("textEdit")
        self.radioButton = QtWidgets.QRadioButton(self.page_3)
        self.radioButton.setGeometry(QtCore.QRect(540, 210, 93, 16))
        self.radioButton.setObjectName("radioButton")
        self.checkBox = QtWidgets.QCheckBox(self.page_3)
        self.checkBox.setGeometry(QtCore.QRect(680, 210, 75, 16))
        self.checkBox.setObjectName("checkBox")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.page_2)
        self.calendarWidget.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_6.addWidget(self.calendarWidget)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.buttom_frame)

        self.retranslateUi(ToggleMenu)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ToggleMenu)

    def retranslateUi(self, ToggleMenu):
        _translate = QtCore.QCoreApplication.translate
        ToggleMenu.setWindowTitle(_translate("ToggleMenu", "Form"))
        self.pushButton_home.setText(_translate("ToggleMenu", "HOME"))
        self.pushButton_user.setText(_translate("ToggleMenu", "USER"))
        self.pushButton_setting.setText(_translate("ToggleMenu", "SETTING"))
        self.label.setText(_translate("ToggleMenu", "Hello PyQt"))
        self.radioButton.setText(_translate("ToggleMenu", "RadioButton"))
        self.checkBox.setText(_translate("ToggleMenu", "CheckBox"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ToggleMenu = QtWidgets.QWidget()
    ui = Ui_ToggleMenu()
    ui.setupUi(ToggleMenu)
    ToggleMenu.show()
    sys.exit(app.exec_())
